# Generated by Django 4.2.16 on 2024-12-05 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('smpl_info_seq', models.AutoField(primary_key=True, serialize=False)),
                ('smpl_id', models.IntegerField(null=True)),
            ],
        ),
    ]
