# Generated by Django 4.2.16 on 2025-02-03 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_bach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCoordiInfo',
            fields=[
                ('meta_coordi_info_seq', models.AutoField(primary_key=True, serialize=False)),
                ('smpl_info_seq', models.IntegerField()),
                ('bar_code', models.CharField(max_length=20)),
                ('visium_spatial_rna_cnt', models.IntegerField(null=True)),
                ('visium_spatial_gene_cnt', models.IntegerField(null=True)),
                ('sct_spatial_umi_cnt', models.IntegerField(null=True)),
                ('sct_spatial_gene_cnt', models.IntegerField(null=True)),
                ('umap_clustr_no', models.IntegerField(null=True)),
                ('each_smpl_rgin', models.CharField(max_length=20)),
                ('intgrt_clustr_no', models.IntegerField(null=True)),
                ('intgrt_clustr_rgin', models.CharField(max_length=20)),
                ('tissue_no', models.IntegerField(null=True)),
                ('row_lc', models.IntegerField(null=True)),
                ('col_lc', models.IntegerField(null=True)),
                ('img_row_lc', models.IntegerField(null=True)),
                ('img_col_lc', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleCellUmapInfo',
            fields=[
                ('single_cell_umap_info_seq', models.AutoField(primary_key=True, serialize=False)),
                ('smpl_info_seq', models.IntegerField()),
                ('single_cell_bar_code', models.CharField(max_length=60)),
                ('clustrs_no', models.IntegerField(null=True)),
                ('fine_celltype', models.CharField(max_length=30)),
                ('main_celltype', models.CharField(max_length=30)),
                ('umap_1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('umap_2', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VisiumExprssionInfo',
            fields=[
                ('visium_exprss_Info_seq', models.AutoField(primary_key=True, serialize=False)),
                ('smpl_info_seq', models.IntegerField()),
                ('bar_code', models.CharField(max_length=20)),
                ('gene_nm', models.CharField(max_length=20)),
                ('express_val', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisiumUmapInfo',
            fields=[
                ('visium_umap_info_seq', models.AutoField(primary_key=True, serialize=False)),
                ('smpl_info_seq', models.IntegerField()),
                ('visium_bar_code', models.CharField(max_length=60)),
                ('visium_clustrs_no', models.IntegerField(null=True)),
                ('visium_region', models.CharField(max_length=30)),
                ('umap_1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('umap_2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('smpl_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_bach.sampleinfo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visiumexprssioninfo',
            constraint=models.UniqueConstraint(fields=('smpl_info_seq', 'bar_code', 'gene_nm'), name='VisiumExprssionInfo Unique IDX 1'),
        ),
        migrations.AddField(
            model_name='singlecellumapinfo',
            name='smpl_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_bach.sampleinfo'),
        ),
        migrations.AddField(
            model_name='metacoordiinfo',
            name='smpl_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_bach.sampleinfo'),
        ),
        migrations.AddConstraint(
            model_name='metacoordiinfo',
            constraint=models.UniqueConstraint(fields=('smpl_info_id', 'bar_code'), name='MetaCoordiInfo Unique IDX 1'),
        ),
    ]
