# Generated by Django 4.2.16 on 2025-02-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_bach', '0002_metacoordiinfo_singlecellumapinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacoordiinfo',
            name='smpl_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_bach.sampleinfo'),
        ),
    ]
