# Generated by Django 4.2.16 on 2025-02-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_bach', '0003_alter_metacoordiinfo_smpl_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlecellumapinfo',
            name='smpl_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_bach.sampleinfo'),
        ),
        migrations.AlterField(
            model_name='visiumumapinfo',
            name='smpl_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_bach.sampleinfo'),
        ),
    ]
